ARG CADDY_VERSION=2

FROM caddy:${CADDY_VERSION}-builder-alpine AS builder

RUN xcaddy build \
  --with github.com/mholt/caddy-l4 \
  --with github.com/caddyserver/transform-encoder \
  --with github.com/fhuteau/caddy-crowdsec-bouncer/http@main \
  --with github.com/fhuteau/caddy-crowdsec-bouncer/appsec@main \
  --with github.com/fhuteau/caddy-crowdsec-bouncer/layer4@main

FROM caddy:${CADDY_VERSION}

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
